title: Github Pages
author: harsh
email: harsh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blogging site

# social links
twitter_username: _i_mharsh
github_username:  harsh123151

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
